# $Id$

PROG=	spectrogram
SRCS=	spectrogram.c alsa.c fft.c cms.c aux.c
BINDIR=	/usr/local/bin
LIBS=	fftw3 x11 alsa
PCCF!=	pkg-config --cflags ${LIBS}
PCLA!=	pkg-config --libs ${LIBS}
CFLAGS+=${PCCF}
LDADD+=	${PCLA}
DEBUG+=	-Wall
NOMAN=

.include <bsd.prog.mk>
